# -*- coding: utf-8 -*-
"""Clase_18/2/2021.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SPMIYy3OeWuL9_GEVAOVKVnotlEOju9M
"""

import numpy as np
from numpy import linalg as LA

A = np.array ([[1,2],[4,5]])
v = np.array ([1,3])
w = np.dot (A,v)
print (w)

LA.norm(w)

np.sqrt(7**2 +19**2)

def norm3(a):
  p = (a[0])**3 + w[1]**3)**(1/3)
  return p

def normp (x,p):
  n = len(x)
  sum = 0.0
  for I in range(n):
    sum = sum + x[I] **p
  z = sum**(1/p)
  return z

x = np.array([1,2,3,7,3])

print(normp(x,4))